name: CI

on:
  push:
    paths:
      - '.SRCINFO'
      - 'PKGBUILD'
  workflow_dispatch:
    inputs:
      version:
        description: 'Upstream synced version'
        default: ''
        required: false

jobs:
  build:
    name: Build package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2

      - name: Build & validate package
        uses: datakrama/archlinux-package-action@v1

  release:
    name: Release package
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
        with:
          persist-credentials: false
          fetch-depth: 0
          ref: main

      - name: Commit changes
        run: |
          if [[ -z "${{ github.event.inputs.version }}" ]]; then
            COMMIT_MESSAGE="chore: update AUR package"
          elif [[ -n "${{ github.event.inputs.version }}" ]]; then
            COMMIT_MESSAGE="chore: bump to v${{ github.event.inputs.version }}"
          fi

          git config --local user.name "${{ secrets.GIT_USERNAME }}"
          git config --local user.email ${{ secrets.GIT_EMAIL }}
          git checkout aur
          git checkout main PKGBUILD .SRCINFO
          git add PKGBUILD .SRCINFO
          git commit -m "$COMMIT_MESSAGE"

      - name: Push changes to GitHub
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: aur

      - name: Push changes to AUR
        uses: datakrama/push-aur-action@v1
        with:
          pkgname: ${{ github.event.repository.name }}
          git_username: ${{ secrets.GIT_USERNAME }}
          git_email: ${{ secrets.GIT_EMAIL }}
          private_ssh_key: ${{ secrets.AUR_PRIVATE_SSH_KEY }}
